version: 0.2


        
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
      - command
  pre_build:
    commands:
      - echo pre_build
      - command
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo postbuild
artifacts:
  files:
    - target\spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.jar
